### ISSUE TITLE
How to I start the playground locally on my laptop? 

### ISSUE THREAD

**Issue by erlebach** [vuesomedev/vue-3-playground#8]
Hi, 

I have downloaded the Playground, which looks very interesting, onto my laptop. 
I then executed: 
```
npm install
npm run serve
``` 
and got the error: 
```
npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/erlebach/.npm/_logs/2021-06-21T18_30_41_455Z-debug.log
```
Any insight would be appreciated. Thanks.

**Comment by sonicoder86** [comment]
Hi,

it only had the `start` command. I've added `serve` as a convenience script. https://github.com/vuesomedev/vue-3-playground/commit/6b655474aec10285f8d7e68cef77eceeb3b0db6b
